### ISSUE TITLE
I'm getting these errors one after the other every time when I'm trying to open in Windows 10

### ISSUE THREAD

**Issue by haseebpvt** [sivasankarankb/breaks#1]
![image](https://user-images.githubusercontent.com/17351945/88480554-33c62100-cf74-11ea-803f-34cf32925113.png)
![image](https://user-images.githubusercontent.com/17351945/88480561-3de81f80-cf74-11ea-9e66-fe5c2515cc7f.png)
![image](https://user-images.githubusercontent.com/17351945/88480571-46d8f100-cf74-11ea-881c-ce15251375b9.png)

**Comment by sivasankarankb** [comment]
(Probably) Because I was building a Windows app on linux (with Wine). Building on a true windows machine seems to solve the problem. It's a DLL compatibility issue. Using official Microsoft DLLs seems to resolve the issue.
