### ISSUE TITLE
Create requirements.txt for non build run

### ISSUE THREAD

**Issue by HashimJVZ** [sivasankarankb/breaks#3]
I just tried to run the app.py in python, it gives me some errors like the module not being found. It will be helpful if you create a requirements.txt file that includes the libraries need to run this app. so that if someone wants to just run the application without building it.

**Comment by sivasankarankb** [comment]
Seems like a nice idea. I'll probably do this or think of some other alternative for this problem. :+1:

**Comment by sivasankarankb** [comment]
Added it with commit 36e1007.
